### ISSUE TITLE
Re-render/redraw graph

### ISSUE THREAD

**Issue by MotionPhix** [stack-stark/ngx-g2plot#2]
How do we call the redraw method to display new data fetched from backend?

**Comment by stack-stark** [comment]
Sorry, I neglected to redraw the problem, it is a serious bug and I will fix it in the near future

**Comment by MotionPhix** [comment]
Alright, noted. By the way, thanks for your great work, your library has by
far solved more issues g2plot was giving me (on its own)....

**Comment by stack-stark** [comment]
The good news is that I have found the solution of the problem. 

I'm using exportAs  the deduced updateConfig, changeData, repaint, destroy the four methods, so that you can at any time to change chart.

I will modify all the instructions and then release a new version, which will take some time.

Finally thank you for your question, it makes me progress!

**Comment by MotionPhix** [comment]
Oh, great. Can't wait to see the new features you've added to it.

And you're welcome

**Comment by stack-stark** [comment]
Hi, my friend. I have submitted to update the new version: 0.0.7, the use of the new features see [npmjs](https://www.npmjs.com/package/ngx-g2plot,) thank you for your use.

If there are any problems in the future, you can raise them again. I will try my best to solve and improve them.
